### ISSUE TITLE
MESA-Toolkit doesn't properly install

### ISSUE THREAD

**Issue by m1j09830** [cisagov/mesa-packer#2]
# 🐛 Summary #

MESA-Toolkit (https://github.com/cisagov/mesa-toolkit.git) doesn't properly install due to a change in the file name for the install script. The original version of the install script had capitalization, while the updated version has been modified to all lowercase letters for the file name. This change has affected the install of the toolkit as the scripts can no longer find the file name it's searching for. 

## To reproduce ##

/bin/bash
#### set up necessary environment variables
export OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES # Ansible bug workaround
set +o history
export PKR_VAR_vm_password='RealPasswordHere'
set -o history

#### Build the template
packer init src/base.pkr.hcl
packer build src/base.pkr.hcl

#### Add the tools
packer init src/install-tools.pkr.hcl
packer build src/install-tools.pkr.hcl (**The build will fail at this point due to the error mentioned above**)

## Expected behavior ##

The mesa-ops.ova should be built and functional if all went as intended. 

## Any helpful log output or screenshots ##

![image](https://github.com/cisagov/mesa-packer/assets/40894613/98fdda19-fb1f-4852-ae1a-b560817ba3d4)

**Comment by coffeegist** [comment]
Closed by #3
