### ISSUE TITLE
MESA should be moved to Debian rather than Kali to reduce bloat

### ISSUE THREAD

**Issue by CyberDoug** [cisagov/mesa-packer#6]
# 💡 Summary #

MESA should be transitioned to Debian from Kali Linux to reduce system bloat associated with the tools installed on Kali Linux be default. Most of these tools are not used by the MESA Toolkit.

## Motivation and context ##

It was directed that MESA should be moved to Debian, rather than Kali Linux, to reduce the bloat associated with tools installed on Kali Linux by default that are not used by MESA.

## Implementation notes ##

- Changed all references to "kali" to "deb"
- Changed the ISO source, and it's respective checksum file, to reflect Debian's latest image
- Changed all Kali Linux mirrors to reflect Debian mirrors

## Acceptance criteria ##

How do we know when this work is done?

- [x] MESA-Packer successfully builds a base-deb image
- [x] MESA-Packer successfully installs the MESA-Toolkit

**Comment by m1j09830** [comment]
Completed by #7
